#ifndef IOT_CONFIGURATION_H
#define IOT_CONFIGURATION_H

#include "Common.h"

#define CONFIG_WIFI_SSID "SolarEdge"
#define CONFIG_WIFI_PASSWORD "202025992"

#define CONFIG_MQTT_CLIENT_QOS DEFAULT_MQTT_QOS
#define CONFIG_MQTT_CLIENT_MESSAGE_RETAIN_POLICY MQTT_MESSAGE_RETAIN_POLICY_OFF

#define CONFIG_AZURE_FQDN "arduino-test.azure-devices.net"
#define CONFIG_AZURE_DEVICE_ID "test-device"
#define CONFIG_AZURE_DEVICE_KEY "XJ5PFpQcr/yF6JjgJDoWA8N9fG9fw8G3BfFLLZJVgOQ="

#endif
