#ifndef RELATIVE_HUMIDITY_TEMP_SENSOR_CONFIG_H
#define RELATIVE_HUMIDITY_TEMP_SENSOR_CONFIG_H

#define DEFAULT_MEASUREMENT_TIMES 2
#define CONFIG_MEASUREMENT_TIMES (uint8_t)DEFAULT_MEASUREMENT_TIMES
#define DEFAULT_CONFIG_PIN 4
#define CONFIG_PIN (uint8_t) DEFAULT_CONFIG_PIN

#endif