services:
  device-simulator-provisioning:
    image: mcr.microsoft.com/oss/azure-samples/azureiot-simulatordeviceprovisioning
    environment:
      - IotHubConnectionString=${SECRET_STRING} # This is a secret, so it should never be exposed! Make sure access rights are correct.
      - DeviceCount=2 # Change this to the desired number of simulated devices. Keep in mind, that the telemetry sending must be modified to match it.
  device-simulator-telemetry:
    image: mcr.microsoft.com/oss/azure-samples/azureiot-telemetrysimulator
    environment:
      - DeviceCount=2
      - IotHubConnectionString=${SECRET_STRING} # This is a secret, so it should never be exposed! Make sure access rights are correct.
      - File=/config-files/telemetry-configuration.json
    volumes:
      - ./configuration:/config-files
