#ifndef DHT_CONFIG_H
#define DHT_CONFIG_H

#define DHT_TYPE_DHT11 DHT11
#define DEFAULT_DHT_TYPE DHT_TYPE_DHT11
#define CONFIG_DHT_TYPE DEFAULT_DHT_TYPE

#if CONFIG_DHT_TYPE == DHT_TPYE_DHT11
    #define DHT_SAMPLING_PERIOD (uint32_t)2000
#endif

#endif // DHT_CONFIG_H
