#ifndef RELATIVE_HUMIDITY_TEMP_SENSOR_CONFIG_HPP
#define RELATIVE_HUMIDITY_TEMP_SENSOR_CONFIG_HPP

#define DEFAULT_MEASUREMENT_TIMES 1
#define CONFIG_MEASUREMENT_TIMES (uint8_t) DEFAULT_MEASUREMENT_TIMES
#define DEFAULT_CONFIG_PIN 4
#define CONFIG_PIN (uint8_t) DEFAULT_CONFIG_PIN

#endif // RELATIVE_HUMIDITY_TEMP_SENSOR_CONFIG_HPP
